import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types .`.

export type Posts = Models.Row & {
    userId: string;
    content: string;
    draft: boolean;
    shortDescription: string;
    title: string;
    thumbnail: string | null;
    creationDate: string;
    updateDate: string | null;
    slug: string;
    views: number;
}
