import { type Models } from 'node-appwrite';

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l ts D:\Dev\Web\bypixel.dev`.
 */

export type Posts = Models.Document & {
  content: string;
  postId: string;
  postSlug: string;
  removed: boolean;
  userId: string;
  shortDescription: string;
  isDraft: boolean;
}

export type Users = Models.Document & {
  discordId: number;
}

