import { type Models } from 'node-appwrite';

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l ts D:\Dev\Web\bypixel.dev`.
 */

export type Posts = Models.Document & {
  userId: string;
  content: string;
  draft: boolean;
  shortDescription: string;
  title: string;
  thumbnail: string | null;
  creationDate: string;
  updateDate: string | null;
  postSlug: string;
  views: number;
}

export type Users = Models.Document & {
  discordId: number;
}

